/**
 * Generates the committed serverless artifact `api/coach.js` from `src/api/coach.ts`.
 *
 * Why a generated, committed bundle: the platform's TypeScript-based function build
 * repeatedly shipped a function with no entry point (FUNCTION_INVOCATION_FAILED on
 * every request), and the failure was invisible from the repository. A pre-bundled,
 * dependency-free plain-JS file removes the host's compiler from the equation: any
 * compile it would do is a no-op, and the file's shape (ESM, one export) is exactly
 * what the runtime expects.
 *
 * The bundle is committed, so this script runs only when the handler changes —
 * regenerate with `npm run build:function` after editing `src/api/coach.ts`.
 *
 * Output is excluded from lint and tests via tsconfig/vitest globs.
 */
import esbuild from 'esbuild';

const functions = [
  { entryPoints: ['src/api/coach.ts'], outfile: 'api/coach.js' },
  { entryPoints: ['src/api/market.ts'], outfile: 'api/market.js' },
];

for (const fn of functions) {
  await esbuild.build({
    ...fn,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'node22',
    banner: {
      js: [
        '// Generated by scripts/bundle-coach.ts — do not edit by hand.',
        '// Regenerate with `npm run build:function` after changing src/api/*.ts.',
      ].join('\n'),
    },
    sourcemap: false,
    logLevel: 'info',
  });
  console.log(`Wrote ${fn.outfile}.`);
}

console.log('Commit these files together with their sources under src/api/.');
