/**
 * Generates the committed serverless artifact `api/coach.js` from `src/api/coach.ts`.
 *
 * Why a generated, committed bundle: the platform's TypeScript-based function build
 * repeatedly shipped a function with no entry point (FUNCTION_INVOCATION_FAILED on
 * every request), and the failure was invisible from the repository. A pre-bundled,
 * dependency-free plain-JS file removes the host's compiler from the equation: any
 * compile it would do is a no-op, and the file's shape (ESM, one export) is exactly
 * what the runtime expects.
 *
 * The bundle is committed, so this script runs only when the handler changes —
 * regenerate with `npm run build:function` after editing `src/api/coach.ts`.
 *
 * Output is excluded from lint and tests via tsconfig/vitest globs.
 */
import esbuild from 'esbuild';

const outfile = 'api/coach.js';

await esbuild.build({
  entryPoints: ['src/api/coach.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'node22',
  // The runtime environment is the API platform itself; declaring these tells
  // esbuild not to replace them and to leave them as ambient globals.
  banner: {
    js: [
      '// Generated by scripts/bundle-coach.ts — do not edit by hand.',
      '// Regenerate with `npm run build:function` after changing src/api/coach.ts.',
    ].join('\n'),
  },
  outfile,
  sourcemap: false,
  logLevel: 'info',
});

console.log(`\nWrote ${outfile}. Commit this file together with src/api/coach.ts.`);
