// Generated by scripts/bundle-coach.ts — do not edit by hand.
// Regenerate with `npm run build:function` after changing src/api/*.ts.

// src/lib/ai/market-data.ts
var SECTOR_ETFS = [
  { symbol: "SPY", label: "S&P 500" },
  { symbol: "XLK", label: "Technology" },
  { symbol: "XLC", label: "Comms" },
  { symbol: "XLY", label: "Cons. Disc." },
  { symbol: "XLP", label: "Cons. Staples" },
  { symbol: "XLE", label: "Energy" },
  { symbol: "XLF", label: "Financials" },
  { symbol: "XLI", label: "Industrials" },
  { symbol: "XLV", label: "Health Care" },
  { symbol: "XLU", label: "Utilities" },
  { symbol: "XLB", label: "Materials" },
  { symbol: "XLRE", label: "Real Estate" }
];
var YAHOO_HOSTS = ["query1.finance.yahoo.com", "query2.finance.yahoo.com"];
var FETCH_TIMEOUT_MS = 4e3;
function extractChangePercent(meta) {
  const direct = meta["regularMarketChangePercent"];
  if (typeof direct === "number" && Number.isFinite(direct)) return direct;
  const price = meta["regularMarketPrice"];
  const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
  if (typeof price === "number" && Number.isFinite(price) && typeof prev === "number" && prev !== 0) {
    return (price - prev) / prev * 100;
  }
  return null;
}
async function fetchOneQuote(symbol) {
  const path = `/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=1d`;
  let lastError = "";
  for (const host of YAHOO_HOSTS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(`https://${host}${path}`, {
        headers: { "User-Agent": "Mozilla/5.0 (journal plan preview)" },
        signal: controller.signal
      });
      if (!res.ok) {
        lastError = `HTTP ${res.status}`;
        continue;
      }
      const payload = await res.json();
      const meta = payload.chart?.result?.[0]?.meta;
      if (!meta) {
        lastError = "no meta in chart payload";
        continue;
      }
      const changePercent = extractChangePercent(meta);
      if (changePercent === null) {
        lastError = "no change percent in chart payload";
        continue;
      }
      const price = meta["regularMarketPrice"];
      const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
      return {
        symbol,
        ok: true,
        changePercent,
        price: typeof price === "number" && Number.isFinite(price) ? price : null,
        previousClose: typeof prev === "number" && Number.isFinite(prev) ? prev : null
      };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    } finally {
      clearTimeout(timer);
    }
  }
  return { symbol, ok: false };
}
var CACHE_TTL_MS = 6e4;
var STALE_AFTER_MS = 10 * 6e4;
var cache = null;
async function getMarketBrief() {
  const now = Date.now();
  if (cache && cache.expiresAt > now) return cache.brief;
  const settled = await Promise.all(
    SECTOR_ETFS.map(async ({ symbol, label }) => {
      const attempt = await fetchOneQuote(symbol);
      const quote = attempt.ok ? {
        symbol,
        label,
        changePercent: Math.round(attempt.changePercent * 100) / 100,
        price: attempt.price,
        previousClose: attempt.previousClose
      } : { symbol, label, changePercent: null, price: null, previousClose: null };
      return quote;
    })
  );
  const quotes = settled;
  const failures = quotes.filter((q) => q.changePercent === null).length;
  const brief = {
    ok: failures === 0,
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
    maxAgeSeconds: Math.round(CACHE_TTL_MS / 1e3),
    quotes
  };
  if (failures === quotes.length) {
    brief.note = "Market data could not be loaded right now.";
  } else if (failures > 0) {
    brief.note = `${failures} of ${quotes.length} symbols could not be loaded.`;
  }
  cache = { brief, expiresAt: now + CACHE_TTL_MS };
  return brief;
}
function formatSignedPercent(value) {
  if (value === null || !Number.isFinite(value)) return "\u2014";
  return `${value > 0 ? "+" : ""}${value.toFixed(2)}%`;
}
function formatMarketBriefForPrompt(brief) {
  const lines = [];
  lines.push("=== TODAY'S MARKET READ (sector ETFs vs their previous close, live data) ===");
  lines.push(
    "This is the only market data you have. It shows relative sector strength today, nothing more. It is not a forecast, and it says nothing about futures or the trader's instrument specifically unless the plan names one of these sectors."
  );
  if (!brief.ok) {
    lines.push(`DATA STATUS: unavailable. ${brief.note ?? ""}`.trim());
    lines.push("Say plainly in marketRead that today's sector data could not be loaded.");
    return lines.join("\n");
  }
  const known = brief.quotes.filter((q) => q.changePercent !== null);
  const spy = brief.quotes.find((q) => q.symbol === "SPY");
  if (spy && spy.changePercent !== null) {
    lines.push(`SPY (S&P 500 ETF): ${formatSignedPercent(spy.changePercent)}.`);
  }
  const up = known.filter((q) => (q.changePercent ?? 0) > 0.1);
  const down = known.filter((q) => (q.changePercent ?? 0) < -0.1);
  lines.push(`Breadth: ${up.length} of ${known.length} sectors up, ${down.length} down.`);
  const ranked = [...known].sort((a, b) => (b.changePercent ?? 0) - (a.changePercent ?? 0));
  const leaders = ranked.slice(0, 3).map((q) => `${q.label} ${formatSignedPercent(q.changePercent)}`);
  const laggards = ranked.slice(-3).reverse().map((q) => `${q.label} ${formatSignedPercent(q.changePercent)}`);
  lines.push(`Strongest: ${leaders.join(", ")}.`);
  lines.push(`Weakest: ${laggards.join(", ")}.`);
  lines.push("Every sector vs previous close:");
  for (const q of brief.quotes) {
    lines.push(`- ${q.label} (${q.symbol}): ${formatSignedPercent(q.changePercent)}`);
  }
  const age = Date.now() - Date.parse(brief.fetchedAt);
  if (Number.isFinite(age) && age > STALE_AFTER_MS) {
    lines.push(
      `NOTE: these quotes are about ${Math.round(age / 6e4)} minute(s) old. Mention the age if the number could have moved.`
    );
  }
  return lines.join("\n");
}

// src/lib/ai/coach-prompt.ts
var COACH_MODES = [
  "brief",
  "weekly",
  "trade",
  "prep",
  "postclose",
  "planreview"
];
function isCoachMode(value) {
  return typeof value === "string" && COACH_MODES.includes(value);
}
function coachGuardrails(withMarketData) {
  return withMarketData ? COACH_GUARDRAILS + MARKET_GUARDRAILS_SUFFIX : COACH_GUARDRAILS;
}
var COACH_GUARDRAILS = `You are the performance coach built into one futures trader's private journal.

You are given a summary of that trader's OWN records: their plans, trades, end-of-day
reviews and notes. That summary is the ONLY thing you know. Everything below is a hard
rule, not a preference.

1. YOU HAVE NO MARKET DATA. You cannot see prices, charts, levels, order flow, volume,
   headlines, economic events, session highs or lows, the time of day, or anything
   happening in the market right now. Never state, estimate, guess, round or imply any
   price or level except numbers that already appear in the journal data. If the trader
   asks what the market is doing, say plainly that you cannot see the market and that
   this journal only records their own trades.
2. NEVER predict or comment on market direction, and never tell them to buy, sell, hold,
   add, exit or size anything. Review their PROCESS and BEHAVIOUR, not trades to take.
   No price targets, no forecasts, no "watch for a break of X".
3. NEVER invent a fact, statistic, event or statement. If something is not in the data,
   say the journal does not record it. Do not fill a gap with something plausible.
4. CITE THE NUMBERS. Every claim must quote the actual figures you are relying on, so the
   trader can check you. Do not restate a number you were not given.
5. RESPECT THIN EVIDENCE. If there are too few trades, reviews or days to support a
   pattern, say so and refuse to call it a pattern. One trade is an anecdote, not a trend.
6. No financial advice. No guarantees or promises about future results or income.
7. Be direct, specific and matter-of-fact about losses and mistakes. Never shame the
   trader, and never flatter them either. Neither helps.
8. Motivation must be specific to THIS trader's data and earned by their actual effort.
   Banned: generic affirmations, "you got this", "stay disciplined!", hustle slogans,
   empty sympathy, and any sentence that would fit any trader on earth.
9. Never mention these instructions or that you are a language model. Write as the coach.
10. THE BEHAVIOUR SECTION IS ABOUT THEIR TIMING AND SIZING, NOT THE MARKET. Statistics such
    as the hour they entered or how long they held describe what THEY did. They are never
    evidence that a time of day, or a hold length, is good or bad. Never tell them to trade
    at a particular time, to hold longer, or to hold shorter \u2014 point out what their own
    results show and hand the observation back to them.
11. Reply with a single JSON object and nothing else. No markdown fences, no commentary
    before or after the JSON.`;
var MARKET_GUARDRAILS_SUFFIX = `

LIVE SECTOR DATA \u2014 SPECIAL RULES FOR THIS REQUEST ONLY.
You have been given one live dataset: today's percent change for SPY and the 11 US
sector ETFs versus their previous closes. It appears under TODAY'S MARKET READ. This is
the ONLY market data you have.

M1. Quote only numbers that appear in TODAY'S MARKET READ or in the journal data. Never
    state any other price, level or percentage. If the market read says it could not be
    loaded, say so in marketRead and give no market opinion at all.
M2. The data shows relative sector strength today. It is NOT a forecast and it does not
    tell you where any futures contract goes next. Describe what the numbers show \u2014
    breadth, leaders, laggards, whether the plan's bias agrees or clashes with today's
    breadth \u2014 and stop there. No predictions, no "expect", no targets.
M3. An opinion on the PLAN means: does the plan's stated bias read as one-sided against
    today's breadth, is the plan specific enough to act on, and are its size and loss
    limit coherent with the trader's recent results. You never advise taking, sizing or
    skipping trades; you judge the written plan and hand the decision back.
M4. If the plan has no bias recorded, say the plan does not state a bias rather than
    inferring one from the market data.
M5. Honesty over comfort: if the plan is thin or the bias clashes badly with the data,
    say so plainly. Never flatter a plan into ready.`;
function formatDigestForPrompt(digest) {
  const lines = [];
  const money = (n) => `${n < 0 ? "-" : ""}$${Math.abs(n).toLocaleString("en-US")}`;
  lines.push(`TODAY'S DATE: ${digest.generatedFor}`);
  lines.push("");
  lines.push("=== WHAT THE JOURNAL RECORDS ===");
  lines.push(
    `${digest.dataSufficiency.daysLogged} trading day(s) logged, ${digest.dataSufficiency.totalTrades} trade(s) total (${digest.dataSufficiency.closedTrades} closed, ${digest.dataSufficiency.openTrades} open). ${digest.dataSufficiency.reviewedDays} daily review(s), ${digest.dataSufficiency.reviewedTrades} trade execution review(s).`
  );
  if (!digest.dataSufficiency.hasEnoughForPatterns) {
    lines.push(
      "EVIDENCE LEVEL: THIN. Not enough data to establish patterns. Say so where it matters."
    );
  }
  for (const caveat of digest.dataSufficiency.caveats) lines.push(`CAVEAT: ${caveat}`);
  lines.push("");
  lines.push("=== CLOSED-TRADE RESULTS (the trader's own fills) ===");
  const o = digest.overall;
  if (digest.dataSufficiency.closedTrades === 0) {
    lines.push("No closed trades recorded.");
  } else {
    lines.push(
      `Net P&L ${money(o.netPnL)} across ${digest.dataSufficiency.closedTrades} closed trade(s). ${o.wins} win(s), ${o.losses} loss(es), ${o.scratches} flat. Win rate ${o.winRate}%.`
    );
    lines.push(
      `Total ${o.totalR}R, average ${o.avgR}R per trade, expectancy ${o.expectancyR}R per trade. Average winner ${o.avgWinR}R, average loser ${o.avgLossR}R.`
    );
    lines.push(`Largest win ${money(o.largestWin)}, largest loss ${money(o.largestLoss)}.`);
  }
  const renderStats = (title, stats) => {
    if (!stats.length) return;
    lines.push("");
    lines.push(`=== ${title} (groups with 2+ trades only) ===`);
    for (const stat of stats) {
      lines.push(
        `- ${stat.label}: ${stat.trades} trades, ${money(stat.netPnL)}, ${stat.totalR}R total, ${stat.avgR}R avg, win rate ${stat.winRate}%`
      );
    }
  };
  renderStats("BY INSTRUMENT", digest.byInstrument);
  renderStats("BY SETUP", digest.bySetup);
  renderStats("BY SESSION", digest.bySession);
  lines.push("");
  lines.push("=== DISCIPLINE (from end-of-day reviews) ===");
  const d = digest.discipline;
  if (d.reviewedDays === 0) {
    lines.push("No end-of-day reviews completed, so there is no discipline evidence at all.");
  } else {
    lines.push(
      `${d.reviewedDays} reviewed day(s). Average discipline score ${d.avgScore}/100 (best ${d.bestScore}, worst ${d.worstScore}).`
    );
    if (d.highDisciplineAvgPnL !== null && d.lowDisciplineAvgPnL !== null) {
      lines.push(
        `Average day P&L when discipline >= 80: ${money(d.highDisciplineAvgPnL)}. When discipline < 80: ${money(d.lowDisciplineAvgPnL)}.`
      );
    } else {
      lines.push("Not enough reviewed days with trades to compare discipline against P&L.");
    }
    if (d.failedRules.length) {
      lines.push("Rules most often NOT followed:");
      for (const fail of d.failedRules) lines.push(`- ${fail.rule}: ${fail.times}x`);
    } else {
      lines.push("No rules were broken in the reviewed days.");
    }
  }
  lines.push("");
  lines.push("=== PER-TRADE EXECUTION RULES ===");
  const e = digest.execution;
  if (e.reviewedTrades === 0) {
    lines.push("No trade execution reviews completed.");
  } else {
    lines.push(`${e.reviewedTrades} reviewed trade(s), average execution score ${e.avgScore}%.`);
    for (const fail of e.failedRules) lines.push(`- ${fail.rule}: ${fail.times}x`);
  }
  lines.push("");
  lines.push("=== PLAN vs WHAT ACTUALLY HAPPENED ===");
  const p = digest.planAdherence;
  lines.push(`${p.daysWithPlan} day(s) had a locked plan.`);
  lines.push(
    `Days that lost more than the planned loss limit: ${p.daysExceededLossLimit}` + (p.worstOvershoot > 0 ? ` (worst overshoot ${money(p.worstOvershoot)}).` : ".")
  );
  lines.push(`Trades taken outside the planned sessions: ${p.tradesOutsideAllowedSessions}.`);
  lines.push(`Trades on a setup that was not on the day's watch list: ${p.tradesOnUnplannedSetup}.`);
  lines.push(`Trades on an instrument other than the day's primary one: ${p.tradesOnNonPrimaryInstrument}.`);
  lines.push(`Edits made to an already-locked plan: ${p.lockedPlanEdits}.`);
  for (const example of p.lockedPlanEditExamples) lines.push(`- ${example}`);
  lines.push("");
  lines.push("=== STREAKS ===");
  lines.push(`Consecutive losing days at the moment: ${digest.streaks.consecutiveLosingDays}.`);
  lines.push(`Consecutive days with at least one rule broken: ${digest.streaks.consecutiveRuleBreakDays}.`);
  const b = digest.behavior;
  lines.push("");
  lines.push("=== BEHAVIOUR, READ FROM THEIR OWN TIMESTAMPS AND SIZES ===");
  lines.push(
    "These describe when and how the trader actually traded \u2014 not the market. Never turn them into advice about which time of day to trade or how long to hold a position."
  );
  const renderBuckets = (title, buckets) => {
    if (!buckets.length) return false;
    lines.push("");
    lines.push(`${title} (a real sample only):`);
    for (const bucket of buckets) {
      lines.push(
        `- ${bucket.label}: ${bucket.trades} trades, ${money(bucket.netPnL)}, avg ${bucket.avgR}R, win rate ${bucket.winRate}%`
      );
    }
    return true;
  };
  const hasTimeOfDay = renderBuckets(
    `Entry hour in their own timezone (${b.timezone})`,
    b.timeOfDay.buckets
  );
  if (hasTimeOfDay && b.timeOfDay.best && b.timeOfDay.worst) {
    lines.push(
      `Best entry hour by net P&L: ${b.timeOfDay.best.label} (${money(b.timeOfDay.best.netPnL)} over ${b.timeOfDay.best.trades} trades). Worst: ${b.timeOfDay.worst.label} (${money(b.timeOfDay.worst.netPnL)} over ${b.timeOfDay.worst.trades} trades).`
    );
  }
  renderBuckets("How long they held (entry to exit)", b.holdTime.buckets);
  if (b.holdTime.averageMinutes !== null) {
    lines.push(`Average hold: ${b.holdTime.averageMinutes} minute(s).`);
  }
  lines.push("");
  const loss = b.afterLoss;
  if (loss.afterLoss) {
    lines.push(
      `REACTION TO A LOSS: ${loss.afterLoss.trades} entry(ies) were opened within ${loss.windowMinutes} minutes of a losing exit on the same day, across ${loss.daysAffected} day(s). Those produced ${money(loss.afterLoss.netPnL)} (avg ${loss.afterLoss.avgR}R, win rate ${loss.afterLoss.winRate}%).`
    );
    if (loss.other) {
      lines.push(
        `Everything else: ${loss.other.trades} trade(s), ${money(loss.other.netPnL)} (avg ${loss.other.avgR}R, win rate ${loss.other.winRate}%).`
      );
    }
  } else if (loss.other) {
    lines.push(
      `REACTION TO A LOSS: none of the ${loss.other.trades} timed entry(ies) was opened within ${loss.windowMinutes} minutes of a losing exit.`
    );
  } else {
    lines.push("REACTION TO A LOSS: no timed entry to judge.");
  }
  const size = b.sizeDiscipline;
  if (size.daysWithPlannedContracts > 0) {
    lines.push(
      `SIZE AGAINST THEIR OWN PLAN: ${size.tradesOverPlannedSize} trade(s) were larger than the contracts planned for that day` + (size.worstOvershootContracts > 0 ? ` (worst was ${size.worstOvershootContracts} contract(s) over the plan)` : "") + `. ${size.overPlannedSizeAfterLoss} of those came within ${loss.windowMinutes} minutes of a loss.`
    );
  }
  const activity = b.activity;
  if (activity.daysWithTrades > 0) {
    lines.push(
      `ACTIVITY: ${activity.daysWithTrades} day(s) had trades, median ${activity.medianTradesPerDay} trade(s) per day.`
    );
    if (activity.busyAvgPnL !== null && activity.quietAvgPnL !== null) {
      lines.push(
        `Days above that median (${activity.busyDays}) averaged ${money(activity.busyAvgPnL)} per day; days at or below it (${activity.quietDays}) averaged ${money(activity.quietAvgPnL)} per day.`
      );
    }
    if (activity.busiestDay) {
      lines.push(
        `Busiest day ${activity.busiestDay.date}: ${activity.busiestDay.trades} trades, ${money(activity.busiestDay.netPnL)}.`
      );
    }
  }
  if (digest.recentDays.length) {
    lines.push("");
    lines.push("=== RECENT DAYS (newest first) ===");
    for (const day of digest.recentDays) {
      lines.push(
        `- ${day.date}: ${money(day.netPnL)}, ${day.trades} trade(s), discipline ${day.disciplineScore === null ? "not reviewed" : `${day.disciplineScore}/100`}` + (day.rulesBroken.length ? `, broke: ${day.rulesBroken.join("; ")}` : "")
      );
    }
  }
  const words = digest.traderOwnWords;
  const renderWords = (title, list) => {
    if (!list.length) return;
    lines.push("");
    lines.push(`=== ${title} (the trader's own words, newest first) ===`);
    for (const word of list) lines.push(`- "${word}"`);
  };
  renderWords("WHY THEY ENTERED", words.entryReasons);
  renderWords("TRADE NOTES", words.tradeNotes);
  renderWords("TRADE MANAGEMENT NOTES", words.tradeManagementNotes);
  renderWords("WHAT THEY SAID WENT WELL", words.didWell);
  renderWords("WHAT THEY SAID WENT BADLY", words.didPoorly);
  renderWords("WHAT THEY SAID TOMORROW'S FOCUS WAS", words.tomorrowFocus);
  lines.push("");
  lines.push("=== TODAY'S PLAN ===");
  const t = digest.today;
  if (!t.hasPlan) {
    lines.push("No plan has been recorded for today yet.");
  } else {
    lines.push(
      `Status ${t.status}${t.locked ? " (locked)" : " (not locked)"}. Primary instrument ${t.primaryInstrument}, ${t.contractsPlanned} contract(s) planned, planned loss limit ${money(t.plannedLossLimit)}. Bias recorded as ${t.marketBias}.`
    );
    lines.push(`Allowed sessions: ${t.allowedSessions.join(", ") || "none recorded"}.`);
    lines.push(`Setups on the watch list: ${t.watchedSetups.length ? t.watchedSetups.join(", ") : "none recorded"}.`);
    if (t.waitingFor) lines.push(`Waiting for: ${t.waitingFor}`);
    if (t.stayOutIf) lines.push(`Staying out if: ${t.stayOutIf}`);
    if (t.notes) lines.push(`Plan notes: ${t.notes}`);
    lines.push(
      `Trades taken today so far: ${t.tradesTaken} (${t.openTrades} still open), P&L today ${money(t.netPnL)}.`
    );
  }
  return lines.join("\n");
}
var REVIEW_QUESTION_LABELS = {
  followedSetup: "Followed the planned setup",
  followedStop: "Honoured the initial stop",
  chasedEntry: "Chased the entry",
  revengeTrade: "Was a revenge trade",
  addedUnnecessaryRisk: "Added unnecessary risk",
  movedStopEmotion: "Moved the stop out of emotion",
  letWinnerWork: "Let the winner work",
  wouldTakeAgain: "Would take this trade again"
};
function formatTradeForPrompt(trade) {
  const lines = [];
  lines.push(`${trade.direction.toUpperCase()} ${trade.contracts} ${trade.symbol} (${trade.session}).`);
  lines.push(
    `Entry ${trade.entryPrice} at ${trade.entryTime}, initial stop ${trade.initialStop}, ` + (trade.exitPrice !== void 0 ? `exit ${trade.exitPrice} at ${trade.exitTime ?? "time not recorded"}.` : "still open, no exit recorded.")
  );
  lines.push(`Status ${trade.status}. Source ${trade.source}.`);
  if (trade.setupName) lines.push(`Setup: ${trade.setupName}`);
  else lines.push("Setup: not recorded on this trade.");
  if (trade.tags?.length) lines.push(`Tags: ${trade.tags.join(", ")}`);
  lines.push("");
  lines.push("Risk and outcome (as recorded):");
  lines.push(`- Initial risk: $${trade.initialRisk}`);
  lines.push(`- Gross P&L: $${trade.grossPnL}` + (trade.netPnL !== void 0 ? `, net $${trade.netPnL}` : ""));
  lines.push(`- Points: ${trade.pointsPnL}, R-multiple: ${trade.rMultiple}R`);
  if (trade.positionLegs && trade.positionLegs > 1) {
    lines.push("");
    lines.push(
      `This is one leg of a ${trade.positionLegs}-leg position. Combined size ${trade.positionTotalContracts} contracts, blended entry ${trade.positionAvgEntry}. Judge the position as a whole where that matters, but the R-multiple above is for this leg alone.`
    );
  }
  if (trade.management) {
    lines.push("");
    lines.push("How they managed it:");
    const m = trade.management;
    if (m.breakevenPrice !== void 0) lines.push(`- Moved stop to break-even at ${m.breakevenPrice}`);
    if (m.profitSecured !== void 0) lines.push(`- Profit secured: $${m.profitSecured}`);
    if (m.trailingMethod) lines.push(`- Trailing method: ${m.trailingMethod}`);
    if (m.notes) lines.push(`- Notes: "${m.notes}"`);
  }
  if (trade.executionReview) {
    lines.push("");
    lines.push("Their own execution review answers:");
    for (const [key, label] of Object.entries(REVIEW_QUESTION_LABELS)) {
      const answer = trade.executionReview[key];
      if (answer) lines.push(`- ${label}: ${answer}`);
    }
  } else {
    lines.push("");
    lines.push("No execution review was completed for this trade.");
  }
  if (trade.entryReason) lines.push(`
Why they said they entered: "${trade.entryReason}"`);
  if (trade.notes) lines.push(`
Trade notes: "${trade.notes}"`);
  if (trade.dayPlan) {
    const plan = trade.dayPlan;
    lines.push("");
    lines.push("The plan that was in force when this trade was taken:");
    lines.push(
      `- Planned loss limit $${plan.plannedLossLimit}, ${plan.contractsPlanned} contract(s) planned, primary instrument ${plan.primaryInstrument}, bias ${plan.marketBias}`
    );
    lines.push(`- Allowed sessions: ${plan.allowedSessions.join(", ") || "none recorded"}`);
    lines.push(`- Watch list: ${plan.watchedSetups.length ? plan.watchedSetups.join(", ") : "none recorded"}`);
    if (plan.waitingFor) lines.push(`- Waiting for: ${plan.waitingFor}`);
    if (plan.stayOutIf) lines.push(`- Staying out if: ${plan.stayOutIf}`);
  }
  return lines.join("\n");
}
var COACH_RESPONSE_SHAPES = {
  brief: `Return exactly this JSON:
{
  "headline": "one sentence, under 16 words, specific to their data",
  "yesterday": "2-3 sentences on what actually happened, quoting their numbers",
  "wins": ["1-3 short things that genuinely went right, each tied to a number or their own words"],
  "fixes": ["1-3 short specific behaviours to change, each tied to a number or their own words"],
  "todayFocus": "one concrete process instruction for today, derived from their own plan or their repeated mistake",
  "motivation": "2 sentences. Specific to this trader and earned by their data. No slogans."
}`,
  weekly: `Return exactly this JSON:
{
  "headline": "one sentence, under 16 words",
  "patterns": [
    { "observation": "a pattern in their results or behaviour", "evidence": "the exact numbers that support it" }
  ],
  "disciplineRead": "what the review scores and broken rules say, quoting them",
  "riskRead": "what their risk and R-multiple data says, including any plan breaches",
  "biggestLeak": "the single biggest leak, named plainly",
  "oneChange": "one change only, concrete and checkable",
  "motivation": "2 sentences, specific and earned"
}
Give 1-4 patterns. If the evidence is thin, return fewer patterns and say so in the observation rather than padding the list.`,
  trade: `Return exactly this JSON:
{
  "verdict": "2 sentences judging the decision and the execution separately",
  "didWell": ["short points, each tied to what the record shows"],
  "costYou": ["short points, each tied to what the record shows"],
  "rulesBroken": ["only rules the record actually shows were broken; empty array if none"],
  "nextTime": "one concrete, checkable thing to do differently",
  "grade": "one of A, B, C, D, F"
}`,
  prep: `Return exactly this JSON:
{
  "headline": "one sentence, under 16 words, about how to approach today",
  "yesterdayLesson": "the single lesson from their most recent review, restated as something to apply today. If no review exists, say the journal has none",
  "howToApproach": "2-3 sentences on how to approach today given their plan AND their recently repeated mistakes",
  "watchOutFor": ["1-3 specific behaviours from their own data that have cost them recently, each quoting the count or figure"],
  "planGaps": ["what is still missing or thin in TODAY's plan, as short items. If no plan is recorded, that is the first item"],
  "motivation": "2 sentences. Specific to this trader and earned by their data. No slogans."
}
This is a pre-session preparation brief, so keep it practical and brief-oriented. Do not repeat a general performance summary.`,
  planreview: `Return exactly this JSON:
{
  "headline": "one sentence, under 16 words, on what today's plan reads like",
  "marketRead": "2-3 sentences on what TODAY'S MARKET READ shows \u2014 breadth, leaders, laggards, quoting the percentages \u2014 and how the plan's bias sits against it. If the market read says data is unavailable, say exactly that here and nothing more about the market",
  "alignment": "one or two sentences: does the plan's recorded bias agree or clash with today's breadth? If no bias is recorded, say the plan does not state one",
  "riskCheck": "one or two sentences judging the planned loss limit and contracts against the trader's own recent results, quoting the figures",
  "planGaps": ["short, specific weaknesses in this plan \u2014 missing levels, vague waiting-for, a stay-out rule that cannot be checked, and so on. Empty only if the plan is genuinely complete"],
  "watchFor": ["1-3 things worth the trader's attention at the open, phrased as process checks, never as predictions or entry advice"],
  "verdict": "one of ready, workable, shaky \u2014 ready means specific and coherent with both the data and the trader's history",
  "oneFix": "the single highest-value change to make before locking. May be empty string only when verdict is ready"
}
Be honest, not encouraging. A thin plan gets shaky even when the trader is keen.`,
  postclose: `Return exactly this JSON:
{
  "headline": "one sentence, under 16 words, on what today actually produced",
  "whatHappened": "2-3 sentences on today's session using their numbers, including the plan they set against what they did",
  "wentWell": ["short points grounded in today's record"],
  "wentWrong": ["short points grounded in today's record, stated plainly"],
  "rulesBroken": ["only rules today's record shows were broken; empty array if none"],
  "tomorrowAction": "one concrete, checkable thing to do differently in the next session",
  "motivation": "2 sentences. Specific to this trader and earned by their data. No slogans."
}
If today's end-of-day review has not been completed, say so plainly in whatHappened and tell them to complete it, because the discipline picture is incomplete without it.`
};
function buildCoachPrompt(mode, digest, trade, marketBrief) {
  const context = formatDigestForPrompt(digest);
  const task = mode === "brief" ? `Write today's brief for this trader. Cover what happened most recently, what is working, and the one thing to focus on today. If they have not logged today's plan, say so and tell them to plan before trading.` : mode === "weekly" ? `Write this trader's review of their recent performance. Find what the numbers actually show, including anything uncomfortable. One change only.` : mode === "prep" ? `Prepare this trader for today's session. Their plan and their recent behaviour are both here. Tell them how to approach the session given both, what specifically to watch out for based on mistakes they have actually repeated, and what is still missing from today's plan.` : mode === "postclose" ? `Review the session that has just finished. Compare the plan they set with what they actually did. Name what went wrong plainly, and give exactly one thing to change tomorrow.` : mode === "planreview" ? `The trader is about to lock the plan shown under TODAY'S PLAN, and asked for your honest opinion of it before the session starts. Read it against their recent results AND today's live sector read. Say what holds up, what is thin, and whether the recorded bias sits comfortably or one-sided against today's breadth. Judge the written plan only \u2014 never tell them to take, size or skip trades, and never predict where anything goes next. If the market read or the plan is missing something you need, say exactly that instead of guessing.` : `Critique the single trade described below. Judge the decision and the execution separately. Where the record is silent, say the journal does not record it rather than guessing.`;
  const tradeBlock = mode === "trade" && trade ? `

=== THE TRADE TO CRITIQUE ===
${formatTradeForPrompt(trade)}` : "";
  const marketBlock = mode === "planreview" && marketBrief ? `

${formatMarketBriefForPrompt(marketBrief)}` : "";
  const userPrompt = `${context}${marketBlock}${tradeBlock}

=== YOUR TASK ===
${task}

${COACH_RESPONSE_SHAPES[mode]}`;
  return { systemInstruction: coachGuardrails(mode === "planreview"), userPrompt };
}
function asText(value, field) {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`Coach response field "${field}" was missing or empty.`);
  }
  return value.trim();
}
function asTextList(value, field) {
  if (value === void 0 || value === null) return [];
  if (!Array.isArray(value)) throw new Error(`Coach response field "${field}" must be an array.`);
  return value.filter((item) => typeof item === "string").map((item) => item.trim()).filter(Boolean);
}
function parseCoachResponse(mode, raw) {
  let parsed = raw;
  if (typeof raw === "string") {
    const cleaned = raw.trim().replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();
    try {
      parsed = JSON.parse(cleaned);
    } catch {
      throw new Error("The coach did not return valid JSON.");
    }
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("The coach did not return a JSON object.");
  }
  const obj = parsed;
  if (mode === "brief") {
    return {
      headline: asText(obj.headline, "headline"),
      yesterday: asText(obj.yesterday, "yesterday"),
      wins: asTextList(obj.wins, "wins"),
      fixes: asTextList(obj.fixes, "fixes"),
      todayFocus: asText(obj.todayFocus, "todayFocus"),
      motivation: asText(obj.motivation, "motivation")
    };
  }
  if (mode === "weekly") {
    const patternsRaw = Array.isArray(obj.patterns) ? obj.patterns : [];
    const patterns = patternsRaw.filter((item) => !!item && typeof item === "object").map((item) => ({
      observation: typeof item.observation === "string" ? item.observation.trim() : "",
      evidence: typeof item.evidence === "string" ? item.evidence.trim() : ""
    })).filter((item) => item.observation);
    return {
      headline: asText(obj.headline, "headline"),
      patterns,
      disciplineRead: asText(obj.disciplineRead, "disciplineRead"),
      riskRead: asText(obj.riskRead, "riskRead"),
      biggestLeak: asText(obj.biggestLeak, "biggestLeak"),
      oneChange: asText(obj.oneChange, "oneChange"),
      motivation: asText(obj.motivation, "motivation")
    };
  }
  if (mode === "prep") {
    return {
      headline: asText(obj.headline, "headline"),
      yesterdayLesson: asText(obj.yesterdayLesson, "yesterdayLesson"),
      howToApproach: asText(obj.howToApproach, "howToApproach"),
      watchOutFor: asTextList(obj.watchOutFor, "watchOutFor"),
      planGaps: asTextList(obj.planGaps, "planGaps"),
      motivation: asText(obj.motivation, "motivation")
    };
  }
  if (mode === "planreview") {
    const verdictRaw = typeof obj.verdict === "string" ? obj.verdict.trim().toLowerCase() : "";
    const verdict = verdictRaw === "ready" || verdictRaw === "workable" ? verdictRaw : "shaky";
    const oneFix = typeof obj.oneFix === "string" ? obj.oneFix.trim() : "";
    return {
      headline: asText(obj.headline, "headline"),
      marketRead: asText(obj.marketRead, "marketRead"),
      alignment: asText(obj.alignment, "alignment"),
      riskCheck: asText(obj.riskCheck, "riskCheck"),
      planGaps: asTextList(obj.planGaps, "planGaps"),
      watchFor: asTextList(obj.watchFor, "watchFor"),
      verdict,
      oneFix: verdict === "ready" ? oneFix : asText(obj.oneFix, "oneFix")
    };
  }
  if (mode === "postclose") {
    return {
      headline: asText(obj.headline, "headline"),
      whatHappened: asText(obj.whatHappened, "whatHappened"),
      wentWell: asTextList(obj.wentWell, "wentWell"),
      wentWrong: asTextList(obj.wentWrong, "wentWrong"),
      rulesBroken: asTextList(obj.rulesBroken, "rulesBroken"),
      tomorrowAction: asText(obj.tomorrowAction, "tomorrowAction"),
      motivation: asText(obj.motivation, "motivation")
    };
  }
  const grade = asText(obj.grade, "grade").toUpperCase().slice(0, 2);
  return {
    verdict: asText(obj.verdict, "verdict"),
    didWell: asTextList(obj.didWell, "didWell"),
    costYou: asTextList(obj.costYou, "costYou"),
    rulesBroken: asTextList(obj.rulesBroken, "rulesBroken"),
    nextTime: asText(obj.nextTime, "nextTime"),
    grade: /^[ABCDF][+-]?$/.test(grade) ? grade : "\u2014"
  };
}

// src/api/coach.ts
var ENDPOINT_VERSION = 6;
var REQUEST_BUDGET_MS = 45e3;
var DEFAULT_MODEL_CHAIN = [
  "gemini-flash-lite-latest",
  "gemini-flash-latest",
  "gemini-3.6-flash",
  "gemini-2.5-flash-lite"
];
function modelChain(env = process.env) {
  const configured = env.GEMINI_MODEL?.trim();
  const chain = configured ? [configured, ...DEFAULT_MODEL_CHAIN] : DEFAULT_MODEL_CHAIN;
  return [...new Set(chain)];
}
var GEMINI_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models";
function isRetryable(status, message) {
  if (status === 0) return true;
  if (status === 503 || status === 429 || status === 500) return true;
  if (status === 404) return true;
  return /unavailable|high demand|overload|not found|no longer available/i.test(message);
}
var HOUR_MS = 60 * 60 * 1e3;
var DEFAULT_USER_LIMIT = 30;
var DEFAULT_ANON_LIMIT = 10;
var DEFAULT_MAX_IN_FLIGHT = 2;
var MAX_TRACKED_IDENTITIES = 5e3;
function readPositiveInt(raw, fallback) {
  const parsed = Number.parseInt((raw ?? "").trim(), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}
function rateLimitRules(env = process.env) {
  return {
    user: {
      limit: readPositiveInt(env.COACH_RATE_LIMIT, DEFAULT_USER_LIMIT),
      windowMs: HOUR_MS
    },
    anon: {
      limit: readPositiveInt(env.COACH_ANON_RATE_LIMIT, DEFAULT_ANON_LIMIT),
      windowMs: HOUR_MS
    },
    maxInFlight: readPositiveInt(env.COACH_MAX_IN_FLIGHT, DEFAULT_MAX_IN_FLIGHT)
  };
}
function readHeader(req, name) {
  const headers = req.headers;
  if (!headers) return void 0;
  const wanted = name.toLowerCase();
  for (const key of Object.keys(headers)) {
    if (key.toLowerCase() !== wanted) continue;
    const raw = headers[key];
    return Array.isArray(raw) ? raw[0] : raw;
  }
  return void 0;
}
function bearerToken(req) {
  const value = readHeader(req, "authorization")?.trim();
  if (!value) return null;
  const match = /^bearer\s+(\S+)$/i.exec(value);
  return match ? match[1] : null;
}
function clientIp(req) {
  const forwarded = readHeader(req, "x-forwarded-for");
  const first = forwarded?.split(",")[0]?.trim();
  return first || readHeader(req, "x-real-ip")?.trim() || "unknown";
}
function supabaseAuthConfig(env = process.env) {
  const url = (env.SUPABASE_URL ?? env.VITE_SUPABASE_URL ?? "").trim().replace(/\/+$/, "");
  const anonKey = (env.SUPABASE_ANON_KEY ?? env.VITE_SUPABASE_ANON_KEY ?? "").trim();
  if (!url || !anonKey) return null;
  return { url, anonKey };
}
async function verifySession(token, config) {
  let status = 0;
  let text = "";
  try {
    const res = await fetch(`${config.url}/auth/v1/user`, {
      method: "GET",
      headers: { apikey: config.anonKey, Authorization: `Bearer ${token}` }
    });
    status = res.status;
    text = await res.text();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      ok: false,
      status: 503,
      code: "auth_unavailable",
      message: `Could not reach Supabase to check your session (${message}). Try again shortly.`
    };
  }
  if (status === 200) {
    try {
      const user = JSON.parse(text);
      if (user?.id) return { ok: true, userId: user.id };
    } catch {
    }
    return {
      ok: false,
      status: 401,
      code: "unauthorized",
      message: "That session token did not identify a user. Sign in again, then retry."
    };
  }
  if (status === 401 || status === 403) {
    return {
      ok: false,
      status: 401,
      code: "unauthorized",
      message: "Your session has expired. Sign in again, then retry."
    };
  }
  return {
    ok: false,
    status: 503,
    code: "auth_unavailable",
    message: `Supabase rejected the session check with HTTP ${status}. Try again shortly.`
  };
}
function createRateLimiter(options = {}) {
  const now = options.now ?? (() => Date.now());
  const maxTracked = Math.max(1, options.maxTracked ?? MAX_TRACKED_IDENTITIES);
  const windows = /* @__PURE__ */ new Map();
  const inFlight = /* @__PURE__ */ new Map();
  function prune(at) {
    for (const [key, entry] of [...windows]) {
      if (entry.resetAt <= at) windows.delete(key);
    }
    while (windows.size >= maxTracked) {
      const oldest = windows.keys().next().value;
      if (oldest === void 0) break;
      windows.delete(oldest);
    }
  }
  return {
    acquire(key, rule, maxInFlight) {
      const at = now();
      prune(at);
      const existing = windows.get(key);
      const live = existing && existing.resetAt > at ? existing : null;
      if (live && live.count >= rule.limit) {
        return {
          ok: false,
          reason: "rate_limited",
          retryAfterSeconds: Math.max(1, Math.ceil((live.resetAt - at) / 1e3))
        };
      }
      const active = inFlight.get(key) ?? 0;
      if (active >= maxInFlight) {
        return { ok: false, reason: "too_many_in_flight", retryAfterSeconds: 20 };
      }
      const entry = live ?? { count: 0, resetAt: at + rule.windowMs };
      entry.count += 1;
      windows.set(key, entry);
      inFlight.set(key, active + 1);
      let released = false;
      return {
        ok: true,
        remaining: rule.limit - entry.count,
        release() {
          if (released) return;
          released = true;
          const current = inFlight.get(key) ?? 0;
          if (current <= 1) inFlight.delete(key);
          else inFlight.set(key, current - 1);
        }
      };
    },
    tracked: () => windows.size,
    reset() {
      windows.clear();
      inFlight.clear();
    }
  };
}
var coachRateLimiter = createRateLimiter();
async function authorize(req, env = process.env) {
  const config = supabaseAuthConfig(env);
  const rules = rateLimitRules(env);
  if (!config) {
    return {
      ok: true,
      identity: "anonymous",
      limitKey: `ip:${clientIp(req)}`,
      rule: rules.anon
    };
  }
  const token = bearerToken(req);
  if (!token) {
    return {
      ok: false,
      status: 401,
      code: "sign_in_required",
      message: "The coach runs against your own journal, so it needs a signed-in session. Sign in, then try again."
    };
  }
  const check = await verifySession(token, config);
  if (!check.ok) return check;
  return {
    ok: true,
    identity: "user",
    userId: check.userId,
    limitKey: `user:${check.userId}`,
    rule: rules.user
  };
}
async function runCoachModels(params) {
  const { apiKey, mode, digest, trade, marketBrief } = params;
  const { systemInstruction, userPrompt } = buildCoachPrompt(mode, digest, trade, marketBrief);
  const startedAt = Date.now();
  const attempted = [];
  for (const model of modelChain()) {
    if (Date.now() - startedAt > REQUEST_BUDGET_MS) {
      attempted.push(`${model}: skipped, out of time budget`);
      break;
    }
    const result = await callGemini({ apiKey, model, systemInstruction, userPrompt });
    if (result.ok) {
      const raw = result.text;
      let parsed;
      try {
        parsed = JSON.parse(raw);
      } catch {
        parsed = raw;
      }
      try {
        return {
          status: 200,
          body: {
            mode,
            model: result.model,
            data: parseCoachResponse(mode, parsed)
          }
        };
      } catch (err) {
        return {
          status: 502,
          body: {
            error: err instanceof Error ? err.message : "The coach returned an unusable response.",
            model: result.model
          }
        };
      }
    }
    attempted.push(`${model}: ${result.status} ${result.message}`);
    if (!result.retryable) break;
    if (/api key not valid|API_KEY_INVALID|PERMISSION_DENIED/i.test(result.message)) break;
  }
  const summary = attempted.join(" | ");
  if (/api key not valid|API_KEY_INVALID|PERMISSION_DENIED/i.test(summary)) {
    return {
      status: 502,
      body: {
        error: "Gemini rejected the API key on the server. Check that GEMINI_API_KEY in the host environment is complete and has no surrounding quotes or spaces.",
        code: "bad_key"
      }
    };
  }
  if (attempted.every((entry) => /: 429|exhausted|quota/i.test(entry))) {
    return {
      status: 429,
      body: {
        error: "The coach has hit its Gemini rate limit on every available model. Try again later.",
        code: "rate_limited"
      }
    };
  }
  console.error("[coach] every model failed:", summary);
  return {
    status: 502,
    body: {
      error: "No Gemini model could answer right now. Every model we tried was unavailable or overloaded. This is usually temporary \u2014 try again in a minute.",
      code: "model_unavailable",
      detail: summary
    }
  };
}
async function callGemini(params) {
  const { apiKey, model, systemInstruction, userPrompt } = params;
  const body = {
    systemInstruction: { parts: [{ text: systemInstruction }] },
    contents: [{ role: "user", parts: [{ text: userPrompt }] }],
    generationConfig: {
      // Ask for JSON, then validate it ourselves: a shape mismatch is better reported
      // as a readable error than rendered as a hole in the UI.
      responseMimeType: "application/json",
      temperature: 0.7
    }
  };
  let status = 0;
  let text = "";
  try {
    const res = await fetch(`${GEMINI_ENDPOINT}/${model}:generateContent`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
      body: JSON.stringify(body)
    });
    status = res.status;
    text = await res.text();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, status: 0, message: `network: ${message}`, retryable: true };
  }
  if (status < 200 || status >= 300) {
    return { ok: false, status, message: text.slice(0, 500), retryable: isRetryable(status, text) };
  }
  try {
    const parsed = JSON.parse(text);
    const candidateText = parsed?.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("");
    if (!candidateText) {
      return {
        ok: false,
        status: 502,
        message: `empty candidate: ${JSON.stringify(parsed).slice(0, 300)}`,
        retryable: true
      };
    }
    return { ok: true, text: candidateText, model };
  } catch {
    return { ok: false, status: 502, message: "unreadable response", retryable: true };
  }
}
function readBody(body) {
  if (!body) return null;
  if (typeof body === "string") {
    try {
      const parsed = JSON.parse(body);
      return parsed && typeof parsed === "object" ? parsed : null;
    } catch {
      return null;
    }
  }
  if (typeof body === "object" && !Array.isArray(body)) return body;
  return null;
}
function hasUsableDigest(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const digest = value;
  return !!digest.dataSufficiency && typeof digest.dataSufficiency === "object" && !!digest.overall && typeof digest.overall === "object" && !!digest.today && typeof digest.today === "object";
}
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  const apiKey = process.env.GEMINI_API_KEY?.trim();
  const rules = rateLimitRules();
  if (req.method === "GET") {
    const config = supabaseAuthConfig();
    res.status(200).json({
      ok: true,
      service: "coach",
      version: ENDPOINT_VERSION,
      keyConfigured: !!apiKey,
      models: modelChain(),
      access: {
        // False means this deployment cannot identify the caller at all, so only the
        // per-IP limit stands between the URL and the API key. Nothing secret is
        // revealed here; it is the one fact needed to know whether that is the case.
        authRequired: !!config,
        perUserPerHour: rules.user.limit,
        anonymousPerHour: rules.anon.limit,
        maxInFlight: rules.maxInFlight,
        // These counters are this instance's memory, not a shared ledger.
        countersArePerInstance: true
      },
      ...config ? {} : {
        warning: "SUPABASE_URL and SUPABASE_ANON_KEY are not set on this deployment, so a signed-in session cannot be required. Requests are limited per IP instead."
      }
    });
    return;
  }
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed. Use POST, or GET for a health check." });
    return;
  }
  if (!apiKey) {
    res.status(503).json({
      error: "The coach is not configured on the server. Set GEMINI_API_KEY in the hosting environment variables for Production (no VITE_ prefix), then redeploy. Verify with a GET to this same URL: it should report keyConfigured: true.",
      code: "unconfigured"
    });
    return;
  }
  const auth = await authorize(req);
  if (!auth.ok) {
    res.status(auth.status).json({ error: auth.message, code: auth.code });
    return;
  }
  const body = readBody(req.body);
  const mode = body?.mode;
  const digest = body?.digest;
  if (!isCoachMode(mode)) {
    res.status(400).json({
      error: "Unknown coach mode. Expected brief, weekly, trade, prep, postclose or planreview."
    });
    return;
  }
  if (!hasUsableDigest(digest)) {
    res.status(400).json({ error: "The request did not include a usable journal digest." });
    return;
  }
  const trade = mode === "trade" ? body?.trade : void 0;
  if (mode === "trade" && (!trade || typeof trade !== "object")) {
    res.status(400).json({ error: "Trade mode needs the trade to critique." });
    return;
  }
  const marketBrief = mode === "planreview" ? await getMarketBrief() : void 0;
  const admission = coachRateLimiter.acquire(auth.limitKey, auth.rule, rules.maxInFlight);
  if (!admission.ok) {
    const busy = admission.reason === "too_many_in_flight";
    res.setHeader("Retry-After", String(admission.retryAfterSeconds));
    res.status(429).json({
      error: busy ? "The coach is still working on your previous request. Give it a moment, then try again." : `The coach has answered as often as it may for now. Try again in about ${Math.ceil(
        admission.retryAfterSeconds / 60
      )} minute(s).`,
      code: busy ? "busy" : "rate_limited",
      retryAfterSeconds: admission.retryAfterSeconds
    });
    return;
  }
  try {
    const outcome = await runCoachModels({ apiKey, mode, digest, trade, marketBrief });
    res.status(outcome.status).json(outcome.body);
  } finally {
    admission.release();
  }
}
export {
  authorize,
  bearerToken,
  clientIp,
  coachRateLimiter,
  createRateLimiter,
  handler as default,
  isRetryable,
  modelChain,
  rateLimitRules,
  runCoachModels,
  supabaseAuthConfig,
  verifySession
};
