// Generated by scripts/bundle-coach.ts — do not edit by hand.
// Regenerate with `npm run build:function` after changing src/api/*.ts.

// src/lib/ai/market-data.ts
var SECTOR_ETFS = [
  { symbol: "SPY", label: "S&P 500" },
  { symbol: "XLK", label: "Technology" },
  { symbol: "XLC", label: "Comms" },
  { symbol: "XLY", label: "Cons. Disc." },
  { symbol: "XLP", label: "Cons. Staples" },
  { symbol: "XLE", label: "Energy" },
  { symbol: "XLF", label: "Financials" },
  { symbol: "XLI", label: "Industrials" },
  { symbol: "XLV", label: "Health Care" },
  { symbol: "XLU", label: "Utilities" },
  { symbol: "XLB", label: "Materials" },
  { symbol: "XLRE", label: "Real Estate" }
];
var YAHOO_HOSTS = ["query1.finance.yahoo.com", "query2.finance.yahoo.com"];
var FETCH_TIMEOUT_MS = 4e3;
function extractChangePercent(meta) {
  const direct = meta["regularMarketChangePercent"];
  if (typeof direct === "number" && Number.isFinite(direct)) return direct;
  const price = meta["regularMarketPrice"];
  const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
  if (typeof price === "number" && Number.isFinite(price) && typeof prev === "number" && prev !== 0) {
    return (price - prev) / prev * 100;
  }
  return null;
}
async function fetchOneQuote(symbol) {
  const path = `/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=1d`;
  let lastError = "";
  for (const host of YAHOO_HOSTS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(`https://${host}${path}`, {
        headers: { "User-Agent": "Mozilla/5.0 (journal plan preview)" },
        signal: controller.signal
      });
      if (!res.ok) {
        lastError = `HTTP ${res.status}`;
        continue;
      }
      const payload = await res.json();
      const meta = payload.chart?.result?.[0]?.meta;
      if (!meta) {
        lastError = "no meta in chart payload";
        continue;
      }
      const changePercent = extractChangePercent(meta);
      if (changePercent === null) {
        lastError = "no change percent in chart payload";
        continue;
      }
      const price = meta["regularMarketPrice"];
      const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
      return {
        symbol,
        ok: true,
        changePercent,
        price: typeof price === "number" && Number.isFinite(price) ? price : null,
        previousClose: typeof prev === "number" && Number.isFinite(prev) ? prev : null
      };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    } finally {
      clearTimeout(timer);
    }
  }
  return { symbol, ok: false };
}
var CACHE_TTL_MS = 6e4;
var STALE_AFTER_MS = 10 * 6e4;
var cache = null;
async function getMarketBrief() {
  const now = Date.now();
  if (cache && cache.expiresAt > now) return cache.brief;
  const settled = await Promise.all(
    SECTOR_ETFS.map(async ({ symbol, label }) => {
      const attempt = await fetchOneQuote(symbol);
      const quote = attempt.ok ? {
        symbol,
        label,
        changePercent: Math.round(attempt.changePercent * 100) / 100,
        price: attempt.price,
        previousClose: attempt.previousClose
      } : { symbol, label, changePercent: null, price: null, previousClose: null };
      return quote;
    })
  );
  const quotes = settled;
  const failures = quotes.filter((q) => q.changePercent === null).length;
  const brief = {
    ok: failures === 0,
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
    maxAgeSeconds: Math.round(CACHE_TTL_MS / 1e3),
    quotes
  };
  if (failures === quotes.length) {
    brief.note = "Market data could not be loaded right now.";
  } else if (failures > 0) {
    brief.note = `${failures} of ${quotes.length} symbols could not be loaded.`;
  }
  cache = { brief, expiresAt: now + CACHE_TTL_MS };
  return brief;
}

// src/api/market.ts
var ENDPOINT_VERSION = 1;
async function handler(req, res) {
  res.setHeader("Cache-Control", "public, max-age=30, stale-while-revalidate=60");
  if (req.method !== "GET") {
    res.status(405).json({ error: "Method not allowed. Use GET." });
    return;
  }
  try {
    const brief = await getMarketBrief();
    res.status(200).json({
      ok: brief.ok,
      service: "market",
      version: ENDPOINT_VERSION,
      note: brief.note,
      fetchedAt: brief.fetchedAt,
      maxAgeSeconds: brief.maxAgeSeconds,
      quotes: brief.quotes
    });
  } catch (err) {
    res.status(502).json({
      ok: false,
      error: "Market data could not be loaded" + (err instanceof Error ? ` (${err.message})` : "") + "."
    });
  }
}
export {
  handler as default
};
