// Generated by scripts/bundle-coach.ts — do not edit by hand.
// Regenerate with `npm run build:function` after changing src/api/*.ts.

// src/lib/ai/market-data.ts
var SECTOR_ETFS = [
  { symbol: "SPY", label: "S&P 500" },
  { symbol: "XLK", label: "Technology" },
  { symbol: "XLC", label: "Comms" },
  { symbol: "XLY", label: "Cons. Disc." },
  { symbol: "XLP", label: "Cons. Staples" },
  { symbol: "XLE", label: "Energy" },
  { symbol: "XLF", label: "Financials" },
  { symbol: "XLI", label: "Industrials" },
  { symbol: "XLV", label: "Health Care" },
  { symbol: "XLU", label: "Utilities" },
  { symbol: "XLB", label: "Materials" },
  { symbol: "XLRE", label: "Real Estate" }
];
var YAHOO_HOSTS = ["query1.finance.yahoo.com", "query2.finance.yahoo.com"];
var FETCH_TIMEOUT_MS = 4e3;
var FUTURES_QUOTE_SYMBOLS = {
  // Equity index futures, micro and full size.
  MES: "MES=F",
  ES: "ES=F",
  MNQ: "MNQ=F",
  NQ: "NQ=F",
  MYM: "MYM=F",
  YM: "YM=F",
  M2K: "M2K=F",
  RTY: "RTY=F",
  // Metals and energy.
  MGC: "MGC=F",
  GC: "GC=F",
  SIL: "SIL=F",
  SI: "SI=F",
  MCL: "MCL=F",
  CL: "CL=F",
  // FX.
  M6E: "M6E=F",
  "6E": "6E=F"
};
function futuresQuoteSymbol(symbol) {
  const key = (symbol || "").trim().toUpperCase();
  return FUTURES_QUOTE_SYMBOLS[key] ?? null;
}
var INSTRUMENT_CACHE_TTL_MS = 2e4;
var instrumentCache = /* @__PURE__ */ new Map();
function readNumber(meta, key) {
  const value = meta[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}
async function fetchChartMeta(yahooSymbol) {
  const path = `/v8/finance/chart/${encodeURIComponent(yahooSymbol)}?range=1d&interval=5m`;
  for (const host of YAHOO_HOSTS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(`https://${host}${path}`, {
        headers: { "User-Agent": "Mozilla/5.0 (journal coach)" },
        signal: controller.signal
      });
      if (!res.ok) continue;
      const payload = await res.json();
      const meta = payload.chart?.result?.[0]?.meta;
      if (meta) return { ok: true, meta };
    } catch {
    } finally {
      clearTimeout(timer);
    }
  }
  return { ok: false };
}
async function getInstrumentQuote(symbol) {
  const journalSymbol = (symbol || "").trim().toUpperCase();
  const yahooSymbol = futuresQuoteSymbol(journalSymbol);
  const now = Date.now();
  if (!journalSymbol) {
    return {
      ok: false,
      symbol: "",
      yahooSymbol: null,
      price: null,
      previousClose: null,
      changePercent: null,
      dayHigh: null,
      dayLow: null,
      volume: null,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
      note: "No instrument was named, so no live read could be made."
    };
  }
  const cached = instrumentCache.get(journalSymbol);
  if (cached && cached.expiresAt > now) return cached.quote;
  const base = {
    ok: false,
    symbol: journalSymbol,
    yahooSymbol,
    price: null,
    previousClose: null,
    changePercent: null,
    dayHigh: null,
    dayLow: null,
    volume: null,
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
  if (!yahooSymbol) {
    const quote2 = {
      ...base,
      note: `No live quote source is mapped for ${journalSymbol}, so no live read is available for it.`
    };
    instrumentCache.set(journalSymbol, { quote: quote2, expiresAt: now + INSTRUMENT_CACHE_TTL_MS });
    return quote2;
  }
  const attempt = await fetchChartMeta(yahooSymbol);
  if (!attempt.ok) {
    const quote2 = {
      ...base,
      note: `Live data for ${journalSymbol} could not be loaded right now.`
    };
    instrumentCache.set(journalSymbol, { quote: quote2, expiresAt: now + INSTRUMENT_CACHE_TTL_MS });
    return quote2;
  }
  const meta = attempt.meta;
  const price = readNumber(meta, "regularMarketPrice");
  const previousClose = readNumber(meta, "chartPreviousClose") ?? readNumber(meta, "previousClose");
  const directPercent = readNumber(meta, "regularMarketChangePercent");
  const changePercent = directPercent ?? (price !== null && previousClose ? (price - previousClose) / previousClose * 100 : null);
  const quote = {
    ok: price !== null,
    symbol: journalSymbol,
    yahooSymbol,
    price,
    previousClose,
    changePercent: changePercent === null ? null : Math.round(changePercent * 100) / 100,
    dayHigh: readNumber(meta, "regularMarketDayHigh"),
    dayLow: readNumber(meta, "regularMarketDayLow"),
    volume: readNumber(meta, "regularMarketVolume"),
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
  if (!quote.ok) {
    return {
      ...quote,
      note: `Live data for ${journalSymbol} came back without a price.`
    };
  }
  instrumentCache.set(journalSymbol, { quote, expiresAt: now + INSTRUMENT_CACHE_TTL_MS });
  return quote;
}
function extractChangePercent(meta) {
  const direct = meta["regularMarketChangePercent"];
  if (typeof direct === "number" && Number.isFinite(direct)) return direct;
  const price = meta["regularMarketPrice"];
  const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
  if (typeof price === "number" && Number.isFinite(price) && typeof prev === "number" && prev !== 0) {
    return (price - prev) / prev * 100;
  }
  return null;
}
async function fetchOneQuote(symbol) {
  const path = `/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=1d`;
  let lastError = "";
  for (const host of YAHOO_HOSTS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(`https://${host}${path}`, {
        headers: { "User-Agent": "Mozilla/5.0 (journal plan preview)" },
        signal: controller.signal
      });
      if (!res.ok) {
        lastError = `HTTP ${res.status}`;
        continue;
      }
      const payload = await res.json();
      const meta = payload.chart?.result?.[0]?.meta;
      if (!meta) {
        lastError = "no meta in chart payload";
        continue;
      }
      const changePercent = extractChangePercent(meta);
      if (changePercent === null) {
        lastError = "no change percent in chart payload";
        continue;
      }
      const price = meta["regularMarketPrice"];
      const prev = meta["chartPreviousClose"] ?? meta["previousClose"];
      return {
        symbol,
        ok: true,
        changePercent,
        price: typeof price === "number" && Number.isFinite(price) ? price : null,
        previousClose: typeof prev === "number" && Number.isFinite(prev) ? prev : null
      };
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
    } finally {
      clearTimeout(timer);
    }
  }
  return { symbol, ok: false };
}
var CACHE_TTL_MS = 6e4;
var STALE_AFTER_MS = 10 * 6e4;
var cache = null;
async function getMarketBrief() {
  const now = Date.now();
  if (cache && cache.expiresAt > now) return cache.brief;
  const settled = await Promise.all(
    SECTOR_ETFS.map(async ({ symbol, label }) => {
      const attempt = await fetchOneQuote(symbol);
      const quote = attempt.ok ? {
        symbol,
        label,
        changePercent: Math.round(attempt.changePercent * 100) / 100,
        price: attempt.price,
        previousClose: attempt.previousClose
      } : { symbol, label, changePercent: null, price: null, previousClose: null };
      return quote;
    })
  );
  const quotes = settled;
  const failures = quotes.filter((q) => q.changePercent === null).length;
  const brief = {
    ok: failures === 0,
    fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
    maxAgeSeconds: Math.round(CACHE_TTL_MS / 1e3),
    quotes
  };
  if (failures === quotes.length) {
    brief.note = "Market data could not be loaded right now.";
  } else if (failures > 0) {
    brief.note = `${failures} of ${quotes.length} symbols could not be loaded.`;
  }
  cache = { brief, expiresAt: now + CACHE_TTL_MS };
  return brief;
}

// src/api/market.ts
var ENDPOINT_VERSION = 2;
function readQuery(req, name) {
  const raw = req.query?.[name];
  const value = Array.isArray(raw) ? raw[0] : raw;
  return typeof value === "string" ? value.trim() : "";
}
async function handler(req, res) {
  res.setHeader("Cache-Control", "public, max-age=20, stale-while-revalidate=40");
  if (req.method !== "GET") {
    res.status(405).json({ error: "Method not allowed. Use GET." });
    return;
  }
  const symbol = readQuery(req, "symbol");
  try {
    if (symbol) {
      const quote = await getInstrumentQuote(symbol);
      res.status(200).json({
        ok: quote.ok,
        service: "market",
        version: ENDPOINT_VERSION,
        kind: "instrument",
        note: quote.note,
        fetchedAt: quote.fetchedAt,
        instrument: quote
      });
      return;
    }
    const brief = await getMarketBrief();
    res.status(200).json({
      ok: brief.ok,
      service: "market",
      version: ENDPOINT_VERSION,
      kind: "sectors",
      note: brief.note,
      fetchedAt: brief.fetchedAt,
      maxAgeSeconds: brief.maxAgeSeconds,
      quotes: brief.quotes
    });
  } catch (err) {
    res.status(502).json({
      ok: false,
      error: "Market data could not be loaded" + (err instanceof Error ? ` (${err.message})` : "") + "."
    });
  }
}
export {
  handler as default
};
